<a href="https://colab.research.google.com/github/JFMilan06/58013LinearAlgebra/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Not Commutative AB is not equal to BA
import numpy as np
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
B = np.array([[2,2,2],[3,3,3],[4,4,4]])

X = np.dot(A,B)
Y = np.dot(B,A)
print(X)
print(Y)

[[ 9  9  9]
 [18 18 18]
 [27 27 27]]
[[12 12 12]
 [18 18 18]
 [24 24 24]]


In [ ]:
#Associative (AB)C=A(BC)
import numpy as np
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
B = np.array([[2,2,2],[3,3,3],[4,4,4]])
C = np.array([[1,1,2],[1,2,2],[1,2,3]])
X = np.dot(A,np.dot(B,C))
Y = np.dot(np.dot(A,B),C)
print(X)
print(Y)

[[ 27  45  63]
 [ 54  90 126]
 [ 81 135 189]]
[[ 27  45  63]
 [ 54  90 126]
 [ 81 135 189]]


In [ ]:
#Identity IA=A and IA=A
import numpy as np
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
I = np.array([[1,0,0],[0,1,0],[0,0,1]])

X = np.dot(A,I)
Y = np.dot(I,A)
print(X)
print(Y)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
#Distributive A(B+C)=AB+AC
import numpy as np
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
B = np.array([[2,2,2],[3,3,3],[4,4,4]])
C = np.array([[1,1,2],[1,2,2],[1,2,3]])
X = np.dot(A,np.add(B,C))
Y = np.add(np.dot(A,B),np.dot(A,C))
print(X)
print(Y)

[[12 14 16]
 [24 28 32]
 [36 42 48]]
[[12 14 16]
 [24 28 32]
 [36 42 48]]


In [ ]:
#Multiplicative property of zero 0A=0 and A0=0
import numpy as np
A = np.array([[1,1,1],[2,2,2],[3,3,3]])
O = np.array([[0,0,0],[0,0,0],[0,0,0]])

X = np.dot(A,O)
Y = np.dot(O,A)
print(X)
print(Y)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
#Dimension Property The product of an M x N matrix and an N x K matrix is M x K
import numpy as np
A = np.array([[1,1,1],[2,2,2]])
B = np.array([[1,1],[2,2],[3,3]])

X = np.dot(A,B)
print(X)

[[ 6  6]
 [12 12]]
