<a href="https://colab.research.google.com/github/JFMilan06/58013LinearAlgebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1. (20 points) Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.

In [3]:
import numpy as np

A = np.array([1,2,3,4,5,6,7,8,9,10])

print(A)
print(np.multiply(2,A))
print(np.multiply(3,A))
print(np.multiply(4,A))
print(np.multiply(5,A))
print(np.multiply(6,A))
print(np.multiply(7,A))
print(np.multiply(8,A))
print(np.multiply(9,A))
print(np.multiply(10,A))

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]
[ 4  8 12 16 20 24 28 32 36 40]
[ 5 10 15 20 25 30 35 40 45 50]
[ 6 12 18 24 30 36 42 48 54 60]
[ 7 14 21 28 35 42 49 56 63 70]
[ 8 16 24 32 40 48 56 64 72 80]
[ 9 18 27 36 45 54 63 72 81 90]
[ 10  20  30  40  50  60  70  80  90 100]


# Question 2. (10 points) In relation to Question 1, show a solution that doubles all the values of each element.

In [3]:
import numpy as np

A = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.multiply(2,A))

[ 2  4  6  8 10 12 14 16 18 20]


# Question 3. (10 points) Create a square matrix that has a diagonal 1's.

In [9]:
import numpy as np
B = np.eye(3,3)

print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Question 4. (30 points) Create a matrix whose elements are:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
                   Type a python program that can view the size, shape, and dimension of the matrix above.

In [4]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("The size of the matrix is ",matrix.size)
print("The shape of the matrix is ",matrix.shape)
print("The dimension of the matrix is ",len(matrix.shape))

The size of the matrix is  12
The shape of the matrix is  (3, 4)
The dimension of the matrix is  2


# Question 5. (30 points) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

In [19]:
import numpy as numpy
arrayOne = numpy.array([[5,6,9],[21,18,27]])
arrayTwo = numpy.array([[15,33,24],[4,7,1]])

D = arrayOne**2
E = arrayTwo**2
print(D)
print(E)

[[ 25  36  81]
 [441 324 729]]
[[ 225 1089  576]
 [  16   49    1]]
