<a href="https://colab.research.google.com/github/JFMilan06/58013LinearAlgebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Addition

In [14]:
import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

np.add(A,np.add(B,C))

array([ 4,  3, -1])

Vector Subtraction

In [15]:
np.subtract(A,B)

array([-2,  1,  2])

Vector Multiplication

In [17]:
np.multiply(A,B)

A*B

array([3, 2, 0])

Vector Division

In [16]:
np.divide(A,B)

A/B

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C//D

np.array(A/B,dtype=int)

array([0, 2, 0])