<a href="https://colab.research.google.com/github/JFMilan06/58013LinearAlgebra/blob/main/Vector%2C_Spaces_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [11]:
#size, dimension, size
import numpy as np

ball1 = np.array([[1],[2],[3]])
ball2 = np.array([0,1,-1])
print(ball1)

[[1]
 [2]
 [3]]


In [22]:
import numpy as np

ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball= np.shape(ball1)
balls= np.shape(ball2)
z= ball+balls
print(z)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [26]:
#Addition
import numpy as np

A= np.array([4,3])
B= np.array([2,-5])
R= np.add(A,B)

print(R)


[ 6 -2]


In [29]:
#Subtract
import numpy as np

A= np.array([4,3])
B= np.array([2,-5])
R= np.subtract(A,B)

print(R)


[2 8]


In [30]:
#Scalar Product
import numpy as np

A= np.array([4,3])
B= np.array([2,-5])
S=[2]
V= S*A
print(V)


[8 6]


In [33]:
#Dot Product
import numpy as np

A= np.array([4,3])
B= np.array([2,-5])
V= A*B
print(V)


[  8 -15]


In [50]:
#Cross Product
import numpy as np

A= np.array([4,3])
B= np.array([[2],[-5]])
V= A*B
print(V)


[[  8   6]
 [-20 -15]]


In [57]:
#Identity Matrix
import numpy as np
c= np.eye(2,2)
print(c)

#Zero Matrix
d = np.zeros([5,5])
print(d)
#Full Matrix
e = np.full([3,3],7)
print(e)
#Transpose of Matrix
f= np.transpose(V)
print(f)

[[1. 0.]
 [0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[  8 -20]
 [  6 -15]]
