<a href="https://colab.research.google.com/github/JFMilan06/58013LinearAlgebra/blob/main/Vector_Operations2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2,0.2,1])
C = np.array([-0.2,2.1,-1.5])

X = np.add(A,np.add(B,C))
print(X)


[[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]


In [13]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2,0.2,1])
C = np.array([-0.2,2.1,-1.5])

X = np.subtract(A,np.subtract(B,C))
print(X)

[[-0.4  1.5 -2.9]
 [ 4.3  6.2  1.8]
 [-0.6  1.3 -3.1]]


In [14]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2,0.2,1])
C = np.array([-0.2,2.1,-1.5])

X = np.multiply(A,np.multiply(B,C))
print(X)

[[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]


In [15]:
import numpy as np
A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([-0.2,0.2,1])
C = np.array([-0.2,2.1,-1.5])

X = np.divide(A,np.divide(B,C))
print(X)

[[-0.4  -4.2   0.6 ]
 [ 4.3  45.15 -6.45]
 [-0.6  -6.3   0.9 ]]
